# EcoSentinel Advanced Security Configuration
# Comprehensive security settings for production deployment

version: '3.0'

security:
  
  # Multi-Factor Authentication Configuration
  mfa:
    enabled: true
    providers:
      - type: "totp"
        issuer: "EcoSentinel"
        algorithm: "SHA256"
        digits: 6
        period: 30
      - type: "sms"
        provider: "twilio"
        template: "Your EcoSentinel verification code is: {code}"
      - type: "email"
        template: "security/mfa-email.html"
    
    backup_codes:
      enabled: true
      count: 10
      length: 8
    
    recovery:
      enabled: true
      admin_override: true
      audit_log: true

  # Advanced Rate Limiting
  rate_limiting:
    tiers:
      free:
        requests_per_hour: 1000
        burst_limit: 50
        concurrent_connections: 10
      
      premium:
        requests_per_hour: 10000
        burst_limit: 200
        concurrent_connections: 50
      
      enterprise:
        requests_per_hour: 100000
        burst_limit: 1000
        concurrent_connections: 200
    
    endpoints:
      "/api/auth/login":
        requests_per_minute: 5
        window_minutes: 15
        block_duration_minutes: 60
      
      "/api/auth/register":
        requests_per_hour: 10
        window_hours: 24
      
      "/api/data/upload":
        requests_per_minute: 10
        max_file_size_mb: 50
      
      "/api/ai/predict":
        requests_per_minute: 20
        cpu_time_limit_seconds: 30

  # Zero Trust Network Access
  zero_trust:
    enabled: true
    
    device_trust:
      certificate_based: true
      device_registration: required
      compliance_check: true
      jailbreak_detection: true
    
    network_policies:
      - name: "admin_access"
        users: ["admin", "super_admin"]
        networks: ["192.168.1.0/24", "10.0.0.0/8"]
        time_restrictions: "09:00-18:00"
        mfa_required: true
      
      - name: "api_access"
        users: ["api_user", "service_account"]
        networks: ["any"]
        rate_limit: "enterprise"
        api_key_required: true
      
      - name: "data_scientists"
        users: ["data_scientist"]
        resources: ["/api/ai/*", "/api/data/analyze"]
        time_restrictions: "08:00-20:00"
        approval_required: false

  # Advanced Encryption
  encryption:
    algorithms:
      symmetric: "AES-256-GCM"
      asymmetric: "RSA-4096"
      hashing: "SHA-512"
      key_derivation: "PBKDF2-SHA512"
    
    key_management:
      rotation_days: 90
      backup_keys: 3
      escrow_enabled: true
      hsm_enabled: true
      key_ceremony: true
    
    data_classification:
      public:
        encryption: false
        retention_days: 365
      
      internal:
        encryption: "AES-256"
        retention_days: 2555  # 7 years
        access_log: true
      
      confidential:
        encryption: "AES-256-GCM"
        key_rotation_days: 30
        access_approval: true
        audit_trail: true
      
      restricted:
        encryption: "AES-256-GCM"
        hsm_required: true
        dual_control: true
        geographic_restrictions: true

  # Behavioral Analytics
  behavioral_analytics:
    enabled: true
    
    user_profiling:
      login_patterns: true
      api_usage_patterns: true
      geographic_analysis: true
      device_fingerprinting: true
    
    anomaly_detection:
      ml_models:
        - "isolation_forest"
        - "one_class_svm"
        - "autoencoder"
      
      thresholds:
        login_anomaly: 0.3
        api_anomaly: 0.2
        data_access_anomaly: 0.4
      
      actions:
        - type: "alert"
          threshold: 0.5
        - type: "step_up_auth"
          threshold: 0.7
        - type: "account_lock"
          threshold: 0.9

  # Advanced Threat Protection
  threat_protection:
    
    ddos_protection:
      enabled: true
      cloudflare_integration: true
      rate_limiting: true
      geo_blocking: ["CN", "RU", "KP"]  # Example countries
      
      mitigation:
        auto_scaling: true
        traffic_shaping: true
        captcha_challenge: true
        js_challenge: true
    
    web_application_firewall:
      provider: "cloudflare"
      
      rule_sets:
        - "owasp_core"
        - "known_bad_inputs"
        - "wordpress_specific"
        - "custom_ecosentinel"
      
      custom_rules:
        - name: "block_bad_bots"
          pattern: "(bot|crawler|spider|scraper)"
          action: "block"
        
        - name: "rate_limit_api"
          pattern: "/api/*"
          rate_limit: "100/hour"
          action: "challenge"
    
    intrusion_detection:
      network_ids: true
      host_ids: true
      
      signatures:
        - "sql_injection"
        - "xss_attacks"
        - "command_injection"
        - "path_traversal"
        - "malware_uploads"
      
      machine_learning:
        enabled: true
        models: ["anomaly_detection", "threat_classification"]
        training_data_days: 90

  # Secure Development Lifecycle
  sdlc:
    
    code_analysis:
      static_analysis:
        tools: ["sonarqube", "semgrep", "bandit"]
        quality_gates: true
        security_hotspots: true
      
      dynamic_analysis:
        tools: ["owasp_zap", "burp_suite"]
        automated_scanning: true
        penetration_testing: "quarterly"
      
      dependency_scanning:
        tools: ["snyk", "dependabot", "npm_audit"]
        auto_updates: "security_only"
        vulnerability_threshold: "high"
    
    secure_coding:
      standards: ["owasp_top_10", "sans_top_25"]
      training_required: true
      code_review_mandatory: true
      security_champion_program: true
    
    deployment_security:
      infrastructure_as_code: true
      secrets_management: "vault"
      container_scanning: true
      runtime_protection: true

  # Compliance and Governance
  compliance:
    
    frameworks:
      gdpr:
        enabled: true
        data_protection_officer: "dpo@ecosentinel.app"
        lawful_basis: "legitimate_interest"
        retention_policies: true
        right_to_deletion: true
      
      sox:
        enabled: true
        financial_controls: true
        audit_trail: true
        segregation_of_duties: true
      
      iso27001:
        enabled: true
        risk_assessment: "annual"
        security_policy: true
        incident_management: true
      
      hipaa:
        enabled: false  # Enable if handling health data
        business_associate_agreement: false
        encryption_required: true
    
    audit_logging:
      retention_years: 7
      immutable_logs: true
      log_encryption: true
      centralized_logging: true
      
      events:
        - "authentication"
        - "authorization"
        - "data_access"
        - "configuration_changes"
        - "privilege_escalation"
        - "data_export"

  # Incident Response
  incident_response:
    
    team:
      incident_commander: "security@ecosentinel.app"
      technical_lead: "devops@ecosentinel.app"
      communications_lead: "pr@ecosentinel.app"
      legal_counsel: "legal@ecosentinel.app"
    
    procedures:
      identification:
        automated_detection: true
        manual_reporting: true
        threat_intelligence_feeds: true
      
      containment:
        network_isolation: true
        account_suspension: true
        service_degradation: true
      
      eradication:
        malware_removal: true
        vulnerability_patching: true
        system_rebuilding: true
      
      recovery:
        service_restoration: true
        monitoring_enhancement: true
        lessons_learned: true
    
    communication:
      internal_notification_minutes: 15
      customer_notification_hours: 24
      regulatory_notification_hours: 72
      public_disclosure_days: 90

  # Business Continuity
  business_continuity:
    
    backup_strategy:
      frequency: "hourly"
      retention: "7_years"
      encryption: true
      geographic_distribution: true
      automated_testing: "weekly"
    
    disaster_recovery:
      rto_minutes: 60  # Recovery Time Objective
      rpo_minutes: 15  # Recovery Point Objective
      
      scenarios:
        - "data_center_failure"
        - "cyber_attack"
        - "natural_disaster"
        - "pandemic"
      
      testing:
        frequency: "quarterly"
        full_scale_testing: "annual"
    
    high_availability:
      multi_region: true
      auto_failover: true
      load_balancing: true
      health_monitoring: true

# Environment-specific configurations
environments:
  
  development:
    security_level: "basic"
    logging_level: "debug"
    encryption: "optional"
    mfa: false
    rate_limiting: "relaxed"
  
  staging:
    security_level: "enhanced"
    logging_level: "info"
    encryption: "required"
    mfa: true
    rate_limiting: "normal"
    penetration_testing: true
  
  production:
    security_level: "maximum"
    logging_level: "warn"
    encryption: "required"
    mfa: true
    rate_limiting: "strict"
    waf: true
    ddos_protection: true
    behavioral_analytics: true

# Monitoring and Alerting
monitoring:
  
  security_metrics:
    authentication:
      - "failed_login_attempts_per_minute"
      - "successful_login_rate"
      - "mfa_bypass_attempts"
      - "password_reset_requests"
    
    api_security:
      - "api_requests_per_second"
      - "rate_limit_violations"
      - "authentication_errors"
      - "unauthorized_access_attempts"
    
    data_protection:
      - "data_export_requests"
      - "encryption_failures"
      - "data_access_violations"
      - "gdpr_requests"
  
  alerting:
    channels:
      - type: "email"
        recipients: ["security@ecosentinel.app"]
        severity: ["critical", "high"]
      
      - type: "slack"
        webhook: "${SLACK_SECURITY_WEBHOOK}"
        severity: ["critical", "high", "medium"]
      
      - type: "pagerduty"
        service_key: "${PAGERDUTY_SERVICE_KEY}"
        severity: ["critical"]
    
    escalation:
      - level: 1
        time_minutes: 15
        contacts: ["on_call_engineer"]
      
      - level: 2
        time_minutes: 60
        contacts: ["security_team_lead"]
      
      - level: 3
        time_minutes: 240
        contacts: ["ciso", "cto"]
