name: ✨ Feature Request
description: Suggest a new feature for EcoSentinel
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - label: User Interface
        - label: API
        - label: AI/ML
        - label: Mobile App
        - label: Performance
        - label: Security
        - label: Documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Mockups, examples, etc.
